version: "3.3"


services: 
  l3pilotUI:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.deploy
    image: l3pilot/ui:deploy
    ports:
      - "8080:8080"
    depends_on:
      - letsencrypt
    restart: always
    container_name: l3pui-nginx
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/letsencrypt:/config
    environment:
      - URL=l3p.atmosphere.tools
      - VALIDATION=http
      - PUID=0
      - PGID=0
