version: "3.3"

#Needs rebuilding everytime a new package is added 

services: 
  l3pilotUI:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.dev
      args:
        - HTTP_PORT=8080
    image: l3pilot/ui:dev
    ports:
      - "8080:8080"
    volumes:
      - ../src:/app/src
      - ../vue.config.js:/app/vue.config.js
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - VUE_APP_API_URL=https://apil3p.atmosphere.tools/v1
